title: BazhRepo
description: "2023-2024 CSA Notebook"
owner_name: Anthony Bazhenov
github_username: Ant11234
github_repo: "Bazhenov Repository"
baseurl: "/BazhRepo"
future: true
remote_theme: jekyll/minima
minima:
  social_links:
    - { platform: github, user_url: "https://github.com/nighthawkcoders/teacher_portfolio"}
    - { platform: instagram, user_url: "https://x.com/NighthawkCoding/" }
    - { platform: AI Project, user_url: "https://www.youtube.com/@nighthawkcodingsociety2868" }      
# remote_theme: pages-themes/dinky@v0.2.0
# remote_theme: pages-themes/minimal@v0.2.0
# remote_theme: pages-themes/hacker@v0.2.0
# remote_theme: pages-themes/cayman@v0.2.0
# remote_theme: pages-themes/time-machine@v0.2.0
plugins:
- jekyll-remote-theme
header_pages:
  - navigation/blog.md
  - navigation/search.html


